package com.ing_software.forms;

import com.ing_software.Principal;
import com.ing_software.abstraccion.Case;
import com.ing_software.abstraccion.Result;
import com.ing_software.entity.Administrativo;
import com.ing_software.entity.Cuenta;
import com.ing_software.entity.Profesor;
import com.ing_software.servicios.AdministrativoUtilities;
import com.ing_software.servicios.ProfesorUtilities;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import lombok.SneakyThrows;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;

import static com.ing_software.abstraccion.Case.defaultCase;
import static com.ing_software.abstraccion.Case.mcase;
import static com.ing_software.abstraccion.Result.failure;
import static com.ing_software.abstraccion.Result.success;
import static com.ing_software.utils.Patterns.*;
import static com.ing_software.utils.Patterns.passwordPattern;

public class GestionarProfesor extends JFrame {

    ProfesorUtilities servicio = Principal.se.select(ProfesorUtilities.class).get();

    private JPanel gestionProfesorPanel;
    private JList listaProfesores;
    private JButton listarProfesoresButton;
    private JButton editarSeleccionadoButton;
    private JTextField cdi_jtext;
    private JTextField pass_jtext;
    private JTextField nombre_jtext;
    private JTextField telf_jtext;
    private JTextField titu_jtext;
    private JTextField mail_jtext;
    private JButton modificarButton;
    private JButton cancelarButton;
    private JButton nuevoButton;
    private JButton salirButton;
    private JButton registrarButton;
    private JScrollPane scrollPane;

    CompletableFuture<List<Profesor>> aux;
    List<Profesor> disponibles = new ArrayList<>();

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        gestionProfesorPanel = new JPanel();
        gestionProfesorPanel.setLayout(new GridLayoutManager(9, 6, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane = new JScrollPane();
        gestionProfesorPanel.add(scrollPane, new GridConstraints(1, 0, 6, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        listaProfesores = new JList();
        scrollPane.setViewportView(listaProfesores);
        listarProfesoresButton = new JButton();
        listarProfesoresButton.setText("Listar Profesores");
        gestionProfesorPanel.add(listarProfesoresButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        editarSeleccionadoButton = new JButton();
        editarSeleccionadoButton.setText("Editar Seleccionado");
        gestionProfesorPanel.add(editarSeleccionadoButton, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Lista Profesores");
        gestionProfesorPanel.add(label1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Datos Profesor");
        gestionProfesorPanel.add(label2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pass_jtext = new JTextField();
        gestionProfesorPanel.add(pass_jtext, new GridConstraints(2, 5, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Datos Cuenta");
        gestionProfesorPanel.add(label3, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        titu_jtext = new JTextField();
        gestionProfesorPanel.add(titu_jtext, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        mail_jtext = new JTextField();
        mail_jtext.setText("");
        gestionProfesorPanel.add(mail_jtext, new GridConstraints(1, 5, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cdi_jtext = new JTextField();
        gestionProfesorPanel.add(cdi_jtext, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        nombre_jtext = new JTextField();
        gestionProfesorPanel.add(nombre_jtext, new GridConstraints(2, 3, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        telf_jtext = new JTextField();
        gestionProfesorPanel.add(telf_jtext, new GridConstraints(4, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("CDI:");
        gestionProfesorPanel.add(label4, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Mail");
        gestionProfesorPanel.add(label5, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Password");
        gestionProfesorPanel.add(label6, new GridConstraints(2, 4, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Nombre");
        gestionProfesorPanel.add(label7, new GridConstraints(2, 2, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Telefono");
        gestionProfesorPanel.add(label8, new GridConstraints(4, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label9 = new JLabel();
        label9.setText("Titulo");
        gestionProfesorPanel.add(label9, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        modificarButton = new JButton();
        modificarButton.setText("Modificar");
        gestionProfesorPanel.add(modificarButton, new GridConstraints(7, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nuevoButton = new JButton();
        nuevoButton.setText("Nuevo");
        gestionProfesorPanel.add(nuevoButton, new GridConstraints(8, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelarButton = new JButton();
        cancelarButton.setText("Cancelar");
        gestionProfesorPanel.add(cancelarButton, new GridConstraints(7, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        salirButton = new JButton();
        salirButton.setText("Salir");
        gestionProfesorPanel.add(salirButton, new GridConstraints(8, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        registrarButton = new JButton();
        registrarButton.setText("Registrar");
        gestionProfesorPanel.add(registrarButton, new GridConstraints(5, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return gestionProfesorPanel;
    }


    public GestionarProfesor(String title) throws HeadlessException {
        super(title);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setContentPane(gestionProfesorPanel);
        this.pack();
        findFuture();
        scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        listaProfesores.setVisibleRowCount(5);
        listaProfesores.setModel(new DefaultListModel<Profesor>());
        editarSeleccionadoButton.setEnabled(false);

        listaProfesores.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                editarSeleccionadoButton.setEnabled(true);
            }
        });


        listarProfesoresButton.addActionListener(new ActionListener() {
            @SneakyThrows
            @Override
            public void actionPerformed(ActionEvent e) {

                if (disponibles.isEmpty()) {
                    disponibles = aux.get();
                }
                refrescarLista();
            }
        });


        editarSeleccionadoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!listaProfesores.isSelectionEmpty()) {
                    Profesor p = (Profesor) listaProfesores.getSelectedValue();
                    cdi_jtext.setText(p.getCedula());
                    nombre_jtext.setText(p.getNombre());
                    telf_jtext.setText(p.getTelefono());
                    Cuenta tmp = p.getCuenta();
                    mail_jtext.setText(tmp.getNombre());
                    pass_jtext.setText(tmp.getPassword());
                    titu_jtext.setText(p.getTitulo() == null ? "" : p.getTitulo());

                    editarSeleccionadoButton.setEnabled(false);
                    nuevoButton.setEnabled(false);
                    registrarButton.setEnabled(false);

                    modificarButton.setEnabled(true);
                    cancelarButton.setEnabled(true);

                    cdi_jtext.setEditable(false);

                }


            }
        });
        modificarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String cdi = cdi_jtext.getText();
                String nombre = nombre_jtext.getText();
                String telefono = telf_jtext.getText();
                String mail = mail_jtext.getText();
                String pass = pass_jtext.getText();
                String titulo = titu_jtext.getText();

                Result<String> result = Case.match(
                        defaultCase(() -> success("Profesor modificado con Exito!")),
                        mcase(() -> cdi.equals(""), () -> failure("CDI vacio")),
                        mcase(() -> nombre.equals(""), () -> failure("Nombre de Profesor vacio")),
                        mcase(() -> telefono.equals(""), () -> failure("Telefono de Profesor vacio")),
                        mcase(() -> mail.equals(""), () -> failure("Mail de Profesor vacio")),
                        mcase(() -> pass.equals(""), () -> failure("Password de Profesor vacio")),
                        mcase(() -> !cdiPattern.matcher(cdi).matches(), () -> failure("CDI no valido")),
                        mcase(() -> !telefonoPattern.matcher(telefono).matches(), () -> failure("Telefono no valido")),
                        mcase(() -> !emailPattern.matcher(mail).matches(), () -> failure("Mail no valido")),
                        mcase(() -> !passwordPattern.matcher(pass).matches(), () -> failure("La password debe contener: " +
                                "\n-Un numero" +
                                "\n-Una mayuscula y una minuscula" +
                                "\n-Al menos 8 caracteres")));


                result.bind(x ->
                {
                    Profesor aux = null;
                    for (Profesor tmp : disponibles) {
                        if (tmp.getCedula().equals(cdi)) {
                            aux = tmp;
                            disponibles.remove(tmp);
                            break;
                        }
                    }

                    if (aux != null) {
                        aux.setNombre(nombre);
                        aux.setTelefono(telefono);
                        aux.setMail(mail);
                        aux.setTitulo(titulo);

                        Cuenta ctmp = aux.getCuenta();
                        ctmp.setNombre(mail);
                        ctmp.setPassword(pass);

                        servicio.saveProfesor(aux);
                        disponibles.add(aux);
                    }
                    refrescarLista();


                    JOptionPane.showMessageDialog(null, x);
                    clearText();
                    setup();


                }, x -> JOptionPane.showMessageDialog(null, x));
            }
        });


        nuevoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cdi_jtext.setEditable(true);
                modificarButton.setEnabled(false);
                cancelarButton.setEnabled(true);
                nuevoButton.setEnabled(false);
                registrarButton.setEnabled(true);

            }
        });
        cancelarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                clearText();
                cdi_jtext.setEditable(false);
                setup();
            }
        });


        registrarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String cdi = cdi_jtext.getText();
                String nombre = nombre_jtext.getText();
                String telefono = telf_jtext.getText();
                String mail = mail_jtext.getText();
                String pass = pass_jtext.getText();
                String titulo = titu_jtext.getText();

                Result<String> result = Case.match(
                        defaultCase(() -> success("Profesor Registrado con Exito!")),
                        mcase(() -> cdi.equals(""), () -> failure("CDI vacio")),
                        mcase(() -> nombre.equals(""), () -> failure("Nombre de administrador vacio")),
                        mcase(() -> telefono.equals(""), () -> failure("Telefono de administrador vacio")),
                        mcase(() -> mail.equals(""), () -> failure("Mail de administrador vacio")),
                        mcase(() -> pass.equals(""), () -> failure("Password de administrador vacio")),
                        mcase(() -> !cdiPattern.matcher(cdi).matches(), () -> failure("CDI no valido")),
                        mcase(() -> !telefonoPattern.matcher(telefono).matches(), () -> failure("Telefono no valido")),
                        mcase(() -> !emailPattern.matcher(mail).matches(), () -> failure("Mail no valido")),
                        mcase(() -> !passwordPattern.matcher(pass).matches(), () -> failure("La password debe contener: " +
                                "\n-Un numero" +
                                "\n-Una mayuscula y una minuscula" +
                                "\n-Al menos 8 caracteres")));


                result.bind(x ->
                {
                    clearText();
                    setup();
                    Profesor tmp = new Profesor();
                    tmp.setCedula(cdi);
                    tmp.setNombre(nombre);
                    tmp.setTelefono(telefono);
                    tmp.setMail(mail);
                    tmp.setTitulo(titulo);

                    Cuenta ctmp = new Cuenta();
                    ctmp.setNombre(mail);
                    ctmp.setPassword(pass);

                    servicio.persistirProfesor(ctmp, tmp);
                    disponibles.add(tmp);
                    refrescarLista();

                    JOptionPane.showMessageDialog(null, x);
                }, x -> JOptionPane.showMessageDialog(null, x));
            }
        });
        salirButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cerrar();
            }
        });
    }

    private void refrescarLista() {
        listaProfesores.setModel(new DefaultListModel());
        DefaultListModel<Profesor> model = (DefaultListModel) (listaProfesores.getModel());
        disponibles.forEach(model::addElement);
    }

    private void cerrar() {
        this.dispose();
    }

    private void setup() {
        editarSeleccionadoButton.setEnabled(false);
        modificarButton.setEnabled(false);
        cancelarButton.setEnabled(false);
        registrarButton.setEnabled(false);
        nuevoButton.setEnabled(true);
    }

    private void clearText() {
        cdi_jtext.setText("");
        nombre_jtext.setText("");
        telf_jtext.setText("");
        mail_jtext.setText("");
        pass_jtext.setText("");
        titu_jtext.setText("");
    }

    private void findFuture() {
        aux = CompletableFuture.supplyAsync(
                () -> servicio.findAll()
                , Principal.e);
    }


}
